import LinkedList from '../LinkedList';

const linkedList = new LinkedList<string>();

console.log('------------------------ append ------------------------');
linkedList.append('aaa');
linkedList.append('bbb');
linkedList.append('ccc');
linkedList.traverse();
console.log('------------------------ insert ------------------------');
linkedList.insert(0, '000');
linkedList.traverse();
linkedList.insert(2, '222');
linkedList.traverse();
linkedList.insert(5, '666');
linkedList.traverse();
console.log('------------------------ get ------------------------');
console.log(linkedList.get(0));
console.log(linkedList.get(1));
console.log(linkedList.get(2));
console.log(linkedList.get(3));
console.log(linkedList.get(8));
console.log('------------------------ indexOf ------------------------');
console.log(linkedList.indexOf('000'));
console.log(linkedList.indexOf('aaa'));
console.log(linkedList.indexOf('666'));
console.log(linkedList.indexOf('---'));
// console.log('------------------------ update ------------------------');
// linkedList.update(0, '000');
// linkedList.update(1, '111');
// linkedList.update(2, '222');
// linkedList.update(3, '333');
// linkedList.traverse();
console.log('------------------------ removeAt ------------------------');
console.log(linkedList.removeAt(0));
linkedList.traverse();
console.log(linkedList.removeAt(1));
linkedList.traverse();
console.log(linkedList.removeAt(3));
linkedList.traverse();
console.log(linkedList.removeAt(4));
linkedList.traverse();
// console.log('------------------------ remove ------------------------');
// console.log(linkedList.remove('000'));
// linkedList.traverse();
// console.log(linkedList.remove('111'));
// linkedList.traverse();
// console.log(linkedList.remove('333'));
// linkedList.traverse();
// console.log('------------------------ isEmpty ------------------------');
// console.log(linkedList.isEmpty());
// console.log('------------------------ size ------------------------');
// console.log(linkedList.size());
