import CircularLinkedList from '../CircularLinkedList';

const circularList = new CircularLinkedList<string>();

console.log('------------------------ append ------------------------');
circularList.append('aaa');
circularList.append('bbb');
circularList.append('ccc');
circularList.traverse();
console.log('------------------------ insert ------------------------');
circularList.insert(0, '000');
circularList.traverse();
circularList.insert(2, '222');
circularList.traverse();
circularList.insert(5, '666');
circularList.traverse();
// console.log('------------------------ get ------------------------');
// console.log(circularList.get(0));
// console.log(circularList.get(1));
// console.log(circularList.get(2));
// console.log(circularList.get(3));
// console.log(circularList.get(8));
// console.log('------------------------ indexOf ------------------------');
// console.log(circularList.indexOf('000'));
// console.log(circularList.indexOf('aaa'));
// console.log(circularList.indexOf('666'));
// console.log(circularList.indexOf('---'));
// console.log('------------------------ update ------------------------');
// circularList.update(0, '000');
// circularList.update(1, '111');
// circularList.update(2, '222');
// circularList.update(3, '333');
// circularList.traverse();
console.log('------------------------ removeAt ------------------------');
console.log(circularList.removeAt(0));
circularList.traverse();
console.log(circularList.removeAt(1));
circularList.traverse();
console.log(circularList.removeAt(3));
circularList.traverse();
console.log(circularList.removeAt(4));
circularList.traverse();
// console.log('------------------------ remove ------------------------');
// console.log(circularList.remove('000'));
// circularList.traverse();
// console.log(circularList.remove('111'));
// circularList.traverse();
// console.log(circularList.remove('333'));
// circularList.traverse();
console.log('------------------------ isEmpty ------------------------');
console.log(circularList.isEmpty());
console.log('------------------------ size ------------------------');
console.log(circularList.size());
