import DoublyLinkedList from '../DoublyLinkedList';

const doublyList = new DoublyLinkedList<string>();
console.log('------------------------ append ------------------------');
doublyList.append('aaa');
doublyList.append('bbb');
doublyList.append('ccc');
doublyList.traverse();
doublyList.postTraverse();
console.log('------------------------ prepend ------------------------');
doublyList.prepend('000');
doublyList.traverse();
doublyList.postTraverse();
console.log('------------------------ insert ------------------------');
doublyList.insert(0, '000');
doublyList.traverse();
doublyList.insert(2, '222');
doublyList.traverse();
doublyList.insert(5, '666');
doublyList.traverse();
doublyList.postTraverse();
console.log('------------------------ get ------------------------');
console.log(doublyList.get(0));
console.log(doublyList.get(1));
console.log(doublyList.get(2));
console.log(doublyList.get(3));
console.log(doublyList.get(8));
console.log('------------------------ indexOf ------------------------');
console.log(doublyList.indexOf('000'));
console.log(doublyList.indexOf('aaa'));
console.log(doublyList.indexOf('666'));
console.log(doublyList.indexOf('---'));
console.log('------------------------ update ------------------------');
doublyList.update(0, '000');
doublyList.update(1, '111');
doublyList.update(2, 'ccc');
doublyList.update(3, '444');
doublyList.traverse();
doublyList.postTraverse();
console.log('------------------------ removeAt ------------------------');
console.log(doublyList.removeAt(0));
doublyList.traverse();
console.log(doublyList.removeAt(1));
doublyList.traverse();
console.log(doublyList.removeAt(3));
doublyList.traverse();
console.log(doublyList.removeAt(4));
doublyList.traverse();
doublyList.postTraverse();
// console.log('------------------------ remove ------------------------');
// console.log(doublyList.remove('000'));
// doublyList.traverse();
// console.log(doublyList.remove('111'));
// doublyList.traverse();
// console.log(doublyList.remove('333'));
// doublyList.traverse();
console.log('------------------------ isEmpty ------------------------');
console.log(doublyList.isEmpty());
console.log('------------------------ size ------------------------');
console.log(doublyList.size());
